spring:
  main:
    banner-mode: OFF
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME:authenticationdb}"
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  port: 8084
  
management:
  endpoints.web:
    base-path: /
    path-mapping:
      health: health-check
    exposure:
      include:
        - health
  endpoint:
    health:
      probes:
        enabled: true